GET http://localhost:8000/pharmacies

###
GET http://localhost:8000/pharmacies/63f8607755b934277811bda9

###
POST http://localhost:8000/pharmacies
content-type:application/json

{
    "name" : "Health Gurd",
    "email": "example2@example.com",
    "address": {
        "lane": "No 139/A, Dharmapala Mawatha",
        "town" : "Colombo 07",
        "district": "Colombo"
    },
    "phone": "0761234337",
    "licenseNumber": "AAA0002",
    "website": "onlinestore@sunshineholdings.lk",
    "operationgHours": {
        "from": {
            "hour": "19",
            "minute" : "00"
        },
        "to": {
            "hour": "18",
            "minute" : "00"
        }
    },
    "password": "password",
    "owner": {
        "name": "Yathu",
        "email": "example2@example.com",
        "address": "No 139/A, Dharmapala Mawatha, Colombo 07, Sri Lanka",
        "phone": "0769872564",
        "nic" : "199812345678"
    }
}

###
PUT http://localhost:8000/pharmacies/63f8607755b934277811bda9
content-type:application/json

{
    "name" : "Health Gurd 01",
    "email": "example2@example.com",
    "address": {
        "lane": "No 139/A, Dharmapala Mawatha",
        "town" : "Colombo 07",
        "district": "Colombo"
    },
    "phone": "0761234567",
    "licenseNumber": "AAA0001",
    "website": "onlinestore@sunshineholdings.lk",
    "operationgHours": {
        "from": {
            "hour": "09",
            "minute" : "00"
        },
        "to": {
            "hour": "18",
            "minute" : "00"
        }
    },
    "owner": {
        "name": "Yathu",
        "email": "example2@example.com",
        "address": "No 139/A, Dharmapala Mawatha, Colombo 07, Sri Lanka",
        "phone": "",
        "nic" : ""
    }
}

###
DELETE http://localhost:8000/pharmacies/63f8593c090a620500939caf

###
PUT http://localhost:8000/pharmacies/status/63f85e02249f502688db0c8c
content-type:application/json

{
    "enabled": true
}